  type Room {
    id: ID!
    name: String!
    color: String!
  }
  
  type Storage {
    id: ID!
    name: String!
    roomId: ID!
  }

  type Product {
    id: ID!
    name: String!
    storageId: ID!
    category: String!
  }

  type Query {
    rooms: [Room]
    storages: [Storage]
    products: [Product]
  }

  type Mutation {
    addRoom(name: String!, color: String!, id: ID! ): Room @resolver
    removeRoom(id: ID!): Room @resolver
    addStorage(name: String!, id: ID!, roomId: ID!): Storage @resolver
    removeStorage(id: ID!): Storage @resolver
    addProduct(name: String!, storageId: ID!, id: ID!, category: String!): Product @resolver
    removeProduct(id: ID!): Product @resolver
  }

